name: Add github label
on: 
  pull_request:
    types:
      - edited

permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - name: Add Deployment Scheduled Label
      id: deployment-scheduled
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;
          const labels = ['DEPLOYMENT-SCHEDULED'];
          await github.rest.issues.addLabels({
            owner,
            repo,
            issue_number,
            labels

